@port = {{$dotenv PORT}}
@baseUrl = http://localhost:{{port}}

### Add a new user
POST {{baseUrl}}/api/users HTTP/1.1
Content-Type: application/json

{
  "image": "#",
  "email": "muster@muster.de",
  "password": "Test1234",
  "username": "Dee"
}

### Request all users
GET {{baseUrl}}/api/users HTTP/1.1
Accept: application/json 